spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}/engine
    username: engine
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: ${PROFILE:default}
