spring:
  mail:
    host: smtp.mail.ru
    port: 465
    username: meetis228@mail.ru
    password: 1qYkgXKD2ktyxGyvQysa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}/engine
    username: engine
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: ${PROFILE:default}
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
        provider:
          google:
            issuer-uri: https://accounts.google.com