keycloak:
  server-url: ${KEYCLOAK_SERVER_URL}
  password: ${KEYCLOAK_PASSWORD}
  username: ${KEYCLOAK_USERNAME}
  realm: ${KEYCLOAK_REALM}

spring:
  mail:
    host: smtp.mail.ru
    port: 465
    username: meetis228@mail.ru
    password: 1qYkgXKD2ktyxGyvQysa
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            enable: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}/engine
    username: engine
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    active: ${PROFILE:default}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: engine
            client-secret: vGO5fNGTamIVSb3MoH3FS0LvmFfeaPZP
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile, email
        provider:
          keycloak:
            authorization-uri: "http://localhost:8080/realms/engine/protocol/openid-connect/auth"
            token-uri: "http://localhost:8080/realms/engine/protocol/openid-connect/token"
            user-info-uri: "http://localhost:8080/realms/engine/protocol/openid-connect/userinfo"
            issuer-uri: http://localhost:8080/realms/engine
            user-name-attribute: preferred_username
server:
  port: 3000
